CREATE TABLE IF NOT EXISTS doc
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	off INTEGER NOT NULL,
	data BLOB NOT NULL,
	nbytes INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS rows
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	row_index INTEGER,
	data BLOB NOT NULL
);
